export const DATA = {
  labelFileName: "File Name",
  labelFileType: "File Type",
  labelLastModified: "Last Modified",
  msgChooseFile: "Please choose file before pressing the Upload button.",
  msgUploading: "Uploading file. Please wait...",
  msgUpload: "Upload donor's file.",
  msgAddPatient: "Add Patient's details.",
  msgError: "Error occured. Please try again.",
  btnUpload: "Upload!",
  navUpload: "Upload Donors",
  navAddPatient: "Add Patient",
  navBrand: "Plasma Tracker",
  footerContactUs: "Contact Us",
  footerAboutUs: "About Us",
};
